#!/usr/bin/env python3
"""Pre-flight checks before opening an upstream PR (AGENTS.md P17, curation).

Three mechanical guards for the no-AI-attribution experiment, learned the hard
way from the RxJava ban:

  policy  does the target repo ban / require disclosure of AI contributions, or
          need a CLA/DCO?  Skipping this is what put us on a hostile repo.
  tells   does the diff or PR text carry AI fingerprints?  em-dash, anonymous
          inner class (convert to a lambda), narrating comments, LLM prose tics.
  format  which formatter does the repo use, so touched files come out
          byte-indistinguishable from hand-written code.

Never a hard block: exit 0 = clean, exit 2 = warnings to review. The operator
decides per case (policy is a flag, not an auto-skip).

Usage:
  pr_preflight.py policy <repo_dir>
  pr_preflight.py tells  <file ...>                 # .java code and/or text/PR body
  pr_preflight.py format <repo_dir>
  pr_preflight.py all    <repo_dir> <changed_file ...>   # files relative to repo_dir
"""
import sys, os, re, glob

EM, EN = "—", "–"  # em-dash, en-dash

# ---------- policy screen ----------
AI_PAT = re.compile(
    r"\b(ai[- ]?generated|generated by ai|artificial intelligence|llm|chatgpt|"
    r"copilot|ai[- ]?assisted|ai contribution|machine[- ]?generated|ai slop|"
    r"generative ai|large language model|ai[- ]?tool)\b", re.I)
CLA_PAT = re.compile(
    r"\b(contributor license agreement|\bcla\b|\bdco\b|"
    r"developer certificate of origin|signed-off-by|sign the cla|\bicla\b)\b", re.I)
POLICY_GLOBS = ["CONTRIBUTING*", ".github/CONTRIBUTING*", ".github/PULL_REQUEST_TEMPLATE*",
                ".github/pull_request_template*", "README*", ".github/CODE_OF_CONDUCT*",
                "CODE_OF_CONDUCT*", "docs/CONTRIBUTING*", ".github/*.md"]

def _policy_files(repo):
    seen, out = set(), []
    for g in POLICY_GLOBS:
        for p in glob.glob(os.path.join(repo, g)):
            rp = os.path.realpath(p)
            if os.path.isfile(p) and rp not in seen:
                seen.add(rp); out.append(p)
    return out

def screen_policy(repo):
    w = []
    for f in _policy_files(repo):
        try: lines = open(f, errors="ignore").read().splitlines()
        except OSError: continue
        rel = os.path.relpath(f, repo)
        for i, ln in enumerate(lines, 1):
            if AI_PAT.search(ln):
                w.append(("AI-POLICY", rel, i, ln.strip()[:160]))
            if CLA_PAT.search(ln):
                w.append(("CLA/DCO", rel, i, ln.strip()[:160]))
    return w

# ---------- tells lint ----------
# anonymous class of a (likely functional) interface: `new Foo<...>() {`
ANON_CLASS = re.compile(r"\bnew\s+[A-Z][\w.]*\s*(?:<[^;\n]*?>)?\s*\(\s*\)\s*\{")
LLM_PROSE = [re.compile(p, re.I) for p in [
    r"it'?s worth noting", r"\bnot just\b.*\bbut\b", r"\bmoreover\b", r"\bfurthermore\b",
    r"\bin summary\b", r"\boverall,", r"\bdelve\b", r"\bseamless", r"\bunderscore", r"\bnavigat",
]]

def lint_tells(paths):
    w, files = [], []
    for p in paths:
        if os.path.isdir(p):
            files += [f for f in glob.glob(os.path.join(p, "**", "*"), recursive=True)
                      if os.path.isfile(f) and f.endswith((".java", ".md", ".txt"))]
        elif os.path.isfile(p):
            files.append(p)
    for f in files:
        try: txt = open(f, errors="ignore").read()
        except OSError: continue
        is_java = f.endswith(".java")
        for i, ln in enumerate(txt.splitlines(), 1):
            if EM in ln or EN in ln:
                w.append(("EM-DASH", f, i, ln.strip()[:120]))
            if is_java and ANON_CLASS.search(ln):
                w.append(("ANON-CLASS", f, i, ln.strip()[:120]))
            target = (not is_java) or ln.lstrip().startswith(("//", "*"))
            if target:
                for pat in LLM_PROSE:
                    if pat.search(ln):
                        w.append(("LLM-PROSE", f, i, ln.strip()[:120])); break
    return w

# ---------- formatter detect ----------
def detect_format(repo):
    blob = ""
    for g in glob.glob(os.path.join(repo, "**", "build.gradle*"), recursive=True)[:30] + \
             glob.glob(os.path.join(repo, "**", "pom.xml"), recursive=True)[:30]:
        try: blob += open(g, errors="ignore").read()
        except OSError: pass
    low = blob.lower()
    out = []
    if "spotless" in low:
        out.append("spotless -> ./gradlew spotlessApply  (or mvn spotless:apply)")
    if "google-java-format" in low or "googlejavaformat" in low:
        out.append("google-java-format configured in the build")
    if glob.glob(os.path.join(repo, "**", "checkstyle*.xml"), recursive=True) or "checkstyle" in low:
        out.append("checkstyle present -> match its rules (./gradlew checkstyleMain / mvn checkstyle:check)")
    if not out:
        out.append("no formatter config found -> run google-java-format on the touched files to normalize")
    return out

def report(label, warns):
    if not warns:
        print(f"  [{label}] clean")
    for kind, f, i, ln in warns:
        print(f"  [{label}:{kind}] {f}:{i}  {ln}")

def main():
    if len(sys.argv) < 3:
        print(__doc__); sys.exit(1)
    cmd, args = sys.argv[1], sys.argv[2:]
    warns = []
    if cmd in ("policy", "all"):
        w = screen_policy(args[0]); report("POLICY", w); warns += w
    if cmd == "tells":
        w = lint_tells(args); report("TELLS", w); warns += w
    if cmd == "all":
        repo, files = args[0], args[1:]
        paths = [f if os.path.isabs(f) else os.path.join(repo, f) for f in files]
        w = lint_tells(paths); report("TELLS", w); warns += w
    if cmd in ("format", "all"):
        for s in detect_format(args[0]):
            print("  [FORMAT]", s)
    sys.exit(2 if warns else 0)

if __name__ == "__main__":
    main()
